`r opts_chunk$set(echo=F,message=F,cache=T)`

```{r load_and_calculate}
options(width=100)
source("Y_chrom_methylation.R")
```

Trying to test which measure feels better that chrY methylation is represented in female samples less than in male ones
========================================================

Alexander Favorov 
-------------------------------------------------------

### 1 Mar 2014


We will test three measures: the coverage of methylation MACS peaks, their score (summed over chromosome) and their product.
To do this, we use an absurd comparison of methylation of Y-chromosome between males and females.

We will make Wilcoxon test for the Y-chr methylation mesure levels and we will make a test of 1&#39;s for all males against 0&#39;s for all females to have a watermark (the last comparison).

Here is coverage of Y-chromome of all the samples by the methylated peaks, the sum of all the scores and the product of length and scores for all the samples.

```{r print_stats} 
print(Y.chrom.stats)
```

Wilcoxon test of the methylation peaks coverage the Y-chromosome for males/females 

```{r wilcoxon_l} 
print(wilcox.test(Y.chrom.stats$Peak.length.sum[Y.chrom.stats$male],Y.chrom.stats$Peak.length.sum[!Y.chrom.stats$male]))
```
Wilcoxon test of the scores sum of Y-chromosome methylation peaks for males/females 

```{r wilcoxon_s} 
print(wilcox.test(Y.chrom.stats$Peak.score.sum[Y.chrom.stats$male],Y.chrom.stats$Peak.score.sum[!Y.chrom.stats$male]))
```

Wilcoxon test of the scores*length product sum Y-chromosome for males/females 
```{r wilcoxon_ls} 
print(wilcox.test(Y.chrom.stats$Product.sum[Y.chrom.stats$male],Y.chrom.stats$Product.sum[!Y.chrom.stats$male]))
```

The watermark test:  Wilcoxon for 1&#39;s for all males against 0&#39;s for all females.
```{r_watermark_wilcoxon}
one_m<-rep(1,sum(Y.chrom.stats$male))
zero_f<-rep(0,sum(!Y.chrom.stats$male))
#remove ties by adding noise
one_m<-one_m+rnorm(length(one_m),0,0.00001)
zero_f<-zero_f+rnorm(length(zero_f),0,0.00001)
print(wilcox.test(one_m,zero_f))
```
### The best measure is the coverage lenghts.


Technical info
-------------------------------
Clinical data file: `r clinFile`.

Its size and modification time: 
```{r file.info}
file.info(clinFile)[,c('size','mtime')] 
```
Number of records is `r nrow(Clinical)`

Bed files:
```{r bed files}
beds
```
DNAIds not in beds:
```{r not in beds}
DNAids[!bed_available]
```
Beds no in DNAids:
```{r not in DNAids}
beds[!bed_used]
```
