`r opts_chunk$set(echo=F,message=F,cache=F,warning=F)`
<!-- cache is off, we save all the neccessary things in Rda -->

```{r load and calculate}
options(width=100)
source('CytoBandDM.R')
karyotype.stat<-as(karyotype,'data.frame')[,c('seqnames','start','end','name')]
colnames(karyotype.stat)[1]='chrom'

karyotype.stat<-cbind(karyotype.stat,'p.value'=wilcoxon.p.values,'bonferroni'=wilcoxon.p.values.bonferroni,'fdr'=wilcoxon.p.values.fdr,'is.hyper'=normals.are.less.methylated)
```


Which cytobands are differentially methylated in the `r clinFileName` data?
========================================================

Alexander Favorov  
-----------------------------------------------

### `r format(Sys.Date(), "%d %b %Y")` 


We load the cytoband list (karyotype) from the SNPchip, version `r SNPchip.version` we load our MACS as described in <a href=`r clinFile`> `r clinFileName` </a> file. 

Then, for each cytoband we calculate the net length of methylated regions (we read them from to MACS bedfiles) that ovelap with the cytoband in each of the samples.


Thus, for each interval (cytodand) we have a methylated length (coverage) for each sample).
Then, we calculate the Wilcoxon p-value for each cytoband's tumor and normal DM coverages.
We think that a cytoband is differentyally methylated if the p-value is <=0.05. 

### Here is the list of all differentially methylated cytobands, no multiple test correction

```{r print, no correction} 
karyotype.stat.DM<-karyotype.stat[DM.cytobands,]
print.data.frame(karyotype.stat.DM,row.names=FALSE)
```

### Here is the same list with Benjamini-Hoochberg correction
```{r print, with FDR} 
print.data.frame(karyotype.stat[DM.cytobands.fdr,],row.names=FALSE)
```

### And, here is the same list with Bonferroni correction
```{r print, with Bonferroni} 
print.data.frame(karyotype.stat[DM.cytobands.bonferroni,],row.names=FALSE)
```
As far as only one cytoband pass the correction, FDR and Bonferroni are the same. The fdr for the second one is `r wilcoxon.p.values.fdr[order(wilcoxon.p.values.fdr)[2]]` and it is too high. 

Technical info
-------------------------------
Clinical data file: `r clinFile`.

Its size and modification time: 
```{r file.info}
file.info(clinFile)[,c('size','mtime')] 
```
Number of records is `r nrow(Clinical)`

Bed files:
```{r bedsinfolder}
bedsinfolder
```
Beds not used:
```{r not in DNAids}
bedsinfolder[!bed.used]
```

