Which CpG islands are differentially methylated in the 2014-02-06_RO1_Batch1-4_ClinicalData_DeID data?
========================================================

Alexander Favorov  
-----------------------------------------------

### `r format(Sys.Date(), "%d %b %Y")` 

`r opts_chunk$set(echo=F,message=F,cache=F,warning=F)`
<!-- cache is off, we save all the neccessary things in Rda -->

We load the CpG islands list from <a href=http://genome.ucsc.edu/>UCSC</a> DAS server and we load our MACS as described in <a href=..\2014-02-06_RO1_Batch1-4_ClinicalData_DeID.html>2014-02-06_RO1_Batch1-4_ClinicalData_DeID.xls.csv</a> file. 

Then, for each island we calculate the net length of methylated regions (we read them from to MACS bedfiles) that ovelap with the island in each of the samples.

```{r load and calculate}
source('CpGIsDM.R')
```

Thus, for each island we have a methylated length (coverage) for each sample).
Then, we calculate the Wilcoxon p-value for each island's tumor and normal DM coverages.
We think that an island is differentially methylated if the p-value is <=0.05.

### Here is the list of all differentially methylated (p<=0.05) CpG with Bonferroni correction

In the table: TSS near is the closest start of a HGNC gene (according to RefSeq coords) to the island.
position and strand are of the gene. Distance is the distance from the middle of the island to TSS, negative means that the island is in the upstream.
We show Wilcoxon and Fisher's p-values for each island as well as OR and the CI for OR.

<a href=./DM.CpGIs.stat.html>Here is the table in html format</a>

<a download href=./DM.CpGIs.stat.tsv>Here is the table in txt format, to be loaded to excel</a>

Technical info
-------------------------------
Clinical data file: `r clinFile`.

Its size and modification time: 
```{r file.info}
file.info(clinFile)[,c('size','mtime')] 
```
Number of records is `r nrow(Clinical)`

Bed files:
```{r bed files}
beds
```
DNAIds not in beds:
```{r not in beds}
DNAids[!bed_available]
```
Beds no in DNAids:
```{r not in DNAids}
beds[!bed_used]
```

