Which Vista enhancers are differentially methylated in the 2014-02-06_RO1_Batch1-4_ClinicalData_DeID data?
========================================================

Alexander Favorov  
-----------------------------------------------

### `r format(Sys.Date(), "%d %b %Y")` 

`r opts_chunk$set(echo=F,message=F,cache=F,warning=F)`
<!-- cache is off, we save all the neccessary things in Rda -->

We load the list of Vista enhancers from <a href=http://genome.ucsc.edu/>UCSC</a> DAS server and we load our MACS as described in <a href=..\2014-02-06_RO1_Batch1-4_ClinicalData_DeID.html>2014-02-06_RO1_Batch1-4_ClinicalData_DeID.xls.csv</a> file. 

Then, for each Vista enhancer we calculate the net length of methylated regions (we read them from to MACS bedfiles) that ovelap with the enhancer in each of the samples.

```{r load and calculate}
options(width=100)
source('vistaEnhancersDM.R')
```

Thus, for each interval (enhancer) we have a methylated length (coverage) for each sample).
Then, we calculate the Wilcoxon p-value for each enhancer's tumor and normal DM coverages.
We think that an enhancer is differentyally methylated if the p-value is <=0.05. 


### And, here is the list of differentially methylated Vista enhancers with Bonferroni correction
```{r print, with Bonferroni} 
print.data.frame(DM.vistaEnhancers.stat,row.names=FALSE)
```

Technical info
-------------------------------
Clinical data file: `r clinFile`.

Its size and modification time: 
```{r file.info}
file.info(clinFile)[,c('size','mtime')] 
```
Number of records is `r nrow(Clinical)`

Bed files:
```{r bed files}
beds
```
DNAIds not in beds:
```{r not in beds}
DNAids[!bed_available]
```
Beds no in DNAids:
```{r not in DNAids}
beds[!bed_used]
```

